### ISSUE TITLE
[BUG]:  Uint8Array Comparison

### ISSUE THREAD

**Issue by ederaleng** [koinos/koinos-system-contracts-as#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Uint8Array comparison in the vph contract when doing a transfer is not working correctly, I understand that cannot compare a Uint8Array with another Uint8Array, so it is better to convert it to a string and compare the strings

```
let callerData = System.getCaller();
System.require(
   callerData.caller == args.from || System.checkAuthority(authority.authorization_type.contract_call, args.from!),
   'from has not authorized transfer',
   error.error_code.authorization_failure
);
```

### Expected behavior

when converting the Uint8Array to string the verification works correctly

```
let callerData = System.getCaller();
System.require(
   Base58.encode(callerData.caller!) == Base58.encode(args.from!) || System.checkAuthority(authority.authorization_type.contract_call, args.from!),
   'from has not authorized transfer',
   error.error_code.authorization_failure
);
```

### Environment

```markdown
- OS:
```

**Comment by mvandeberg** [comment]
Would you be willing to make a PR for this?

Also, it should probably use `Arrays.equal` instead of encoding the addresses to base 58 and comparing those.

**Comment by ederaleng** [comment]
@mvandeberg of course I can make the PR and you are right it is better with `Arrays.equal`
